### ISSUE TITLE
deletion of a shelf fails

### ISSUE THREAD

**Issue by k3tw13z3l** [Technosoft2000/docker-calibre-web#10]
$ docker inspect -f '{{ index .Config.Labels "image.base.version" }}' calibre-web
3.6-2
$ docker inspect -f '{{ index .Config.Labels "image.version" }}' calibre-web
1.1.6

If I try to delete a shelf in the web interface the calibre-web.log shows:

~~~
{/usr/lib/python2.7/site-packages/flask/app.py:1560} ERROR - Exception on /shelf/delete/1 [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 2201, in delete_shelf
    if deleted:
UnboundLocalError: local variable 'deleted' referenced before assignment
~~~

And I get a 500 internal error page in the browser...

I haven't check the calibre-web code yet...

**Comment by k3tw13z3l** [comment]
I noticed that an admin user can delete its own 'your shelves'. So it seems to be a problem for an extra user.

**Comment by Technosoft2000** [comment]
Hi @k3tw13z3l,

I'll check this issue too, but as I can see in the provided log it is an issue of the application [janeczku/calibre-web](https://github.com/janeczku/calibre-web) self. 
I've checked the issues list there and can't find an entry for such an issue, but after I've successfully reproduced the issue I'll create an issue ticket and link to this one.

**Comment by Technosoft2000** [comment]
Tested with Container version **1.1.8**  and Calibre Web commit **9182d8912816c27e67e452334df370c8fdc89ba4** where it works without any issue, due this I'll close the ticket now.
