### ISSUE TITLE
Upgrade of image failed

### ISSUE THREAD

**Issue by DaveDaveDaveDave** [Technosoft2000/docker-calibre-web#110]
Hello,

I haven't been able to find a similar error to what I'm seeing after and upgrade of the the docker image using the latest tag.  Everything was working properly before the upgrade.

Using latest Docker on Synology NAS.

Load is normal until Calibre Web launch:

`[INFO] Launching Calibre-Web ...                                                                                                                                
Traceback (most recent call last):                                                                                                                              
  File "/Books/calibre-web/app/cps.py", line 37, in <module>                                                                                                    
    from cps.gdrive import gdrive                                                                                                                               
  File "/Books/calibre-web/app/cps/gdrive.py", line 119, in <module>                                                                                            
    @csrf.exempt                                                                                                                                                
AttributeError: 'NoneType' object has no attribute 'exempt'                 `

I have tried rolling back to the earlier docker images, but get the same errors.  I'm not using Google Drive at all.  All library files are local on the NAS.

Any help is appreciated!

**Comment by DaveDaveDaveDave** [comment]
This issue is related to existing issue 109: 

https://github.com/Technosoft2000/docker-calibre-web/issues/109
