### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'config_calibre_dir'

### ISSUE THREAD

**Issue by calibandotexe** [Technosoft2000/docker-calibre-web#12]
**hello technosoft2000**! I was able to get your Docker image installed about a month ago; but I've just tried to reinstall it, and am hitting an error that makes me think there's a compatibility problem with @janeczku's source.

The shell command and output's copied below. What's happening in this `NoneType` for the `self.config_calibre_dir assignment`? Is `config_calibre_dir` something I need to configure at install time, or is it a problem "upstream?"

```
caliban@local:~$ docker run --name=calibre-web --restart=always -v /home/calibre/ebooks:/books -v /etc/localtime:/etc/localtime:ro -e PGID=1003 -e PUID=1003 -p 8083:8083 technosoft2000/calibre-web

Unable to find image 'technosoft2000/calibre-web:latest' locally
latest: Pulling from technosoft2000/calibre-web
2aecc7e1714b: Pull complete
3dab6bea1267: Pull complete
5726cc4cd8fb: Pull complete
38d29c9d393f: Pull complete
75fad1da58dd: Pull complete
be1c8b0850cf: Pull complete
f6cde5373e7a: Pull complete
d4e071ea1734: Pull complete
992c3a14eeb4: Pull complete
Digest: sha256:db92853ebc8720bcb106ce2b32147d9b28e0ab735e1139d2d468070f817ed080
Status: Downloaded newer image for technosoft2000/calibre-web:latest
        ,----,
      ,/   .`|
    ,`   .'  : .--.--.        ,----,        ,-.
  ;    ;     //  /    '.    .'   .' \   ,--/ /|
.'___,/    ,'|  :  /`. /  ,----,'    |,--. :/ |
|    :     | ;  |  |--`   |    :  .  ;:  : ' /
;    |.';  ; |  :  ;_     ;    |.'  / |  '  /
`----'  |  |  \  \    `.  `----'/  ;  '  |  :
    '   :  ;   `----.   \   /  ;  /   |  |   \
    |   |  '   __ \  \  |  ;  /  /-,  '  : |. \
    '   :  |  /  /`--'  / /  /  /.`|  |  | ' \ \
    ;   |.'  '--'.     /./__;      :  '  : |--'
    '---'      `--'---' |   :    .'   ;  |,'
                        ;   | .'      '--'
                        `---'

      PRESENTS ANOTHER AWESOME DOCKER IMAGE

      ~~~~~         Calibre Web       ~~~~~

[INFO] Docker image version: 1.1.7
[INFO] Alpine Linux version: 3.6.0
[INFO] Create group calibre with id 1003
[INFO] Create user calibre with id 1003
[INFO] Current active timezone is EDT
[INFO] Change the ownership of /calibre-web (including subfolders) to calibre:calibre
[INFO] Current git version is:
git version 2.13.5
[INFO] Checkout the latest Calibre-Web version ...
[INFO] ... git clone -b master --single-branch https://github.com/janeczku/calibre-web.git /calibre-web/app -v
Cloning into '/calibre-web/app'...
POST git-upload-pack (189 bytes)
[INFO] Autoupdate is active, try to pull the latest sources for Calibre-Web ...
[INFO] ... current git status is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
a8b53ab38a46158dcd57bccb28805d377a547927
[INFO] ... pulling sources
Already up-to-date.
[INFO] ... git status after update is
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
a8b53ab38a46158dcd57bccb28805d377a547927
[INFO] kindlegen (Amazon Kindle Generator) will be linked into /calibre-web/app/vendor
> create kindlegen link /calibre-web/app/vendor/kindlegen assigned to source /calibre-web/kindlegen/kindlegen
ln: failed to create symbolic link '/calibre-web/app/vendor/kindlegen': No such file or directory
[INFO] Checking permissions of /books
> Output is: 775 calibre 1003 calibre 1003
> Permissions: 775
> Assigned group: calibre
> Assigned group ID: 1003
> Assigned owner: calibre
> Assigned owner ID: 1003
> Using permissions for checks: 0775
> Check if the group calibre has write access at /books
> The group calibre has write access at /books
[INFO] app.db and gdrive.db will be linked into /books
> create app.db link /calibre-web/app/app.db assigned to source /books/app.db
> create gdrive.db link /calibre-web/app/gdrive.db assigned to source /books/gdrive.db
[INFO] Creating directory for temporary directories and files: /tmp
[INFO] Change the ownership of /tmp (including subfolders) to calibre:calibre
[INFO] Launching Calibre-Web ...
Traceback (most recent call last):
  File "/calibre-web/app/cps.py", line 13, in <module>
    from cps import web
  File "/calibre-web/app/cps/web.py", line 30, in <module>
    import ub
  File "/calibre-web/app/cps/ub.py", line 593, in <module>
    config = Config()
  File "/calibre-web/app/cps/ub.py", line 300, in __init__
    self.loadSettings()
  File "/calibre-web/app/cps/ub.py", line 304, in loadSettings
    self.config_calibre_dir = data.config_calibre_dir
AttributeError: 'NoneType' object has no attribute 'config_calibre_dir'
```

**Comment by Technosoft2000** [comment]
Hi @calibandotexe,

I can't reproduce your issue with the actual Calibre Web sources, but I've fixed know the issue with `kindlegen` which I've seen in your log output:
```
[INFO] kindlegen (Amazon Kindle Generator) will be linked into /calibre-web/app/vendor
> create kindlegen link /calibre-web/app/vendor/kindlegen assigned to source /calibre-web/kindlegen/kindlegen
ln: failed to create symbolic link '/calibre-web/app/vendor/kindlegen': No such file or directory
```

Please try my actual image version v1.1.8

Thanks 
TS2k

**Comment by BluebonnetSK** [comment]
I'm having very similar issues to what was posted above and I cannot figure out the problem.  Note, I can successfully run the linuxserver/calibre-web docker, but I want to run this one for the ebook-converter feature.  

The docker can never start, it just keeps trying to start continually.  This section of log just repeats endlessly: 

```
        ,----,                                   ,
      ,/   .`|                                   ,
    ,`   .'  : .--.--.        ,----,        ,-.  ,
  ;    ;     //  /    '.    .'   .' \   ,--/ /|  ,
.'___,/    ,'|  :  /`. /  ,----,'    |,--. :/ |  ,
|    :     | ;  |  |--`   |    :  .  ;:  : ' /   ,
;    |.';  ; |  :  ;_     ;    |.'  / |  '  /    ,
`----'  |  |  \  \    `.  `----'/  ;  '  |  :    ,
    '   :  ;   `----.   \   /  ;  /   |  |   \   ,
    |   |  '   __ \  \  |  ;  /  /-,  '  : |. \  ,
    '   :  |  /  /`--'  / /  /  /.`|  |  | ' \ \ ,
    ;   |.'  '--'.     /./__;      :  '  : |--'  ,
    '---'      `--'---' |   :    .'   ;  |,'     ,
                        ;   | .'      '--'       ,
                        `---'                    ,
,
      PRESENTS ANOTHER AWESOME DOCKER IMAGE,
      ,
      ~~~~~         Calibre Web       ~~~~~,
                                           ,
[INFO] Docker image version: 1.2.3,
[INFO] Alpine Linux version: 3.8.0,
[WARNING] A group with id 1000 exists already [in use by calibre] and will be modified.,
[WARNING] The group calibre will be renamed to calibre,
[WARNING] A user with id 1000 exists already [in use by calibre].,
[WARNING] Create user calibre with temporary user id 999.,
[WARNING] Assign non-unique user id 1000 to created user calibre,
adduser: user 'calibre' in use,
usermod: no changes,
[INFO] Current active timezone is CET,
[INFO] Change the ownership of /calibre-web (including subfolders) to calibre:calibre,
[INFO] Current git version is:,
git version 2.18.0,
[INFO] Checkout the latest Calibre-Web version ...,
[INFO] Autoupdate is active, try to pull the latest sources for Calibre-Web ...,
[INFO] ... current git status is,
On branch master,
Your branch is up to date with 'origin/master'.,
,
nothing to commit, working tree clean,
dfa17956c908b814b035bf942494ba3450beeccf,
FO] ... pulling sources,
Already up to date.,
[INFO] ... git status after update is,
On branch master,
Your branch is up to date with 'origin/master'.,
,
nothing to commit, working tree clean,
dfa17956c908b814b035bf942494ba3450beeccf,
[INFO] Config directory option is DEACTIVATED,
> due this the Calibre books directory /books will be used to store the configuration,
[INFO] Checking permissions of the config directory: /books,
> Output is: 755 calibre 1000 calibre 1000,
> Permissions: 755,
> Assigned group: calibre,
> Assigned group ID: 1000,
> Assigned owner: calibre,
> Assigned owner ID: 1000,
> Using permissions for checks: 0755,
> The user calibre:1000 is the owner and has write access at /books,
[INFO] 'app.db' and 'gdrive.db' will be linked into /books,
> 'app.db' link /calibre-web/app/app.db exists already and won't be recreated,
> 'gdrive.db' link /calibre-web/app/gdrive.db exists already and won't be recreated,
[INFO] Checking permissions of the books directory: /books,
> Output is: 755 calibre 1000 calibre 1000,
> Permissions: 755,
> Assigned group: calibre,
> Assigned group ID: 1000,
> Assigned owner: calibre,
> Assigned owner ID: 1000,
> Using permissions for checks: 0755,
> The user calibre:1000 is the owner and has write access at /books,
[INFO] The mapped volume for /books contains a Calibre database file 'metadata.db' which will be used,
[INFO] The kindlegen directory exist already and will be used: /calibre-web/kindlegen,
[INFO] Kindlegen application exists already in directory: /calibre-web/kindlegen,
[INFO] kindlegen (Amazon Kindle Generator) will be linked into /calibre-web/app/vendor,
> kindlegen link /calibre-web/app/vendor/kindlegen exists already and won't be recreated,
[INFO] Launching Calibre-Web ...,
Traceback (most recent call last):,
  File "/calibre-web/app/cps.py", line 13, in <module>,
    from cps.server import Server,
  File "/calibre-web/app/cps/server.py", line 8, in <module>,
    import web,
  File "/calibre-web/app/cps/web.py", line 16, in <module>,
    import ub,
  File "/calibre-web/app/cps/ub.py", line 782, in <module>,
    config = Config(),
  File "/calibre-web/app/cps/ub.py", line 348, in __init__,
    self.loadSettings(),
  File "/calibre-web/app/cps/ub.py", line 353, in loadSettings,
    self.config_calibre_dir = data.config_calibre_dir,
AttributeError: 'NoneType' object has no attribute 'config_calibre_dir',
```
As a second issue, this line in the log concerns me: 
```[INFO] Config directory option is DEACTIVATED,```
because I have USE_CONFIG_DIR set to true, and have set the following volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/mnt/unionfs/Media/Books/Calibre_Library:/books"
      - "/mnt:/mnt"
      - "/opt/calibre-web/app:/calibre-web/app"
      - "/opt/calibre-web/config:/calibre-web/config"
      - "/opt/calibre-web/kindlegen:/calibre-web/kindlegen"
      - "/opt/calibre:/opt/calibre"

I running this on a headless Ubuntu 18.04.
