### ISSUE TITLE
Calibre Docker under UNRAID refuses connection

### ISSUE THREAD

**Issue by 40foot** [Technosoft2000/docker-calibre-web#125]
Before undergoing heart surgery last November I stopped all my containers on my UNRAID 6.9.3 system, now I tried to restart my CalibreWeb container but the connection is refused. I'm not good at Linux... tried to set the chmod and chown to calibre user and group but still it doesn't allow connections. What can I do? Here is the output from log after starting:

PRESENTS ANOTHER AWESOME DOCKER IMAGE

~~~~~ Calibre Web ~~~~~

[INFO] Docker image version: 1.6.0

[INFO] Alpine Linux version: 3.12.0

[WARNING] A group with id 100 exists already [in use by calibre] and will be modified.

[WARNING] The group calibre will be renamed to calibre

[WARNING] A user with id 99 exists already [in use by calibre].

[WARNING] Create user calibre with temporary user id 999.

adduser: user 'calibre' in use
[WARNING] Assign non-unique user id 99 to created user calibre

usermod: no changes
[INFO] Current active timezone is CET
Sat Feb 4 17:31:31 CET 2023
[INFO] Container timezone is changed to: UTC
[INFO] Change the ownership of /calibre-web (including subfolders) to calibre:calibre
[INFO] Current git version is:

git version 2.26.3

[INFO] Checkout the latest Calibre-Web version ...

[INFO] Autoupdate is active, try to pull the latest sources for Calibre-Web ...
[INFO] ... current git status is
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
cf9a7d538fe39ea356138722f566dfd04bae8b54
[INFO] ... pulling sources
Already up to date.
[INFO] ... git status after update is
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
cf9a7d538fe39ea356138722f566dfd04bae8b54
[INFO] Config directory option is DEACTIVATED
> due this the Calibre books directory /books will be used to store the configuration
[INFO] Checking permissions of the config directory: /books
> Output is: 755 calibre 100 calibre 99
> Permissions: 755
> Assigned group: calibre
> Assigned group ID: 100
> Assigned owner: calibre
> Assigned owner ID: 99
> Using permissions for checks: 0755
> The user calibre:99 is the owner and has write access at /books
[INFO] 'app.db' and 'gdrive.db' will be linked into /books
> create 'app.db' link /calibre-web/app/app.db assigned to source /books/app.db
ln: failed to create symbolic link '/calibre-web/app/app.db': File exists

> change the ownership of /calibre-web/app/app.db to calibre:calibre
> create 'gdrive.db' link /calibre-web/app/gdrive.db assigned to source /books/gdrive.db
> change the ownership of /calibre-web/app/gdrive.db to calibre:calibre
[INFO] Checking permissions of the books directory: /books
> Output is: 755 calibre 100 calibre 99
> Permissions: 755
> Assigned group: calibre
> Assigned group ID: 100
> Assigned owner: calibre
> Assigned owner ID: 99
> Using permissions for checks: 0755
> The user calibre:99 is the owner and has write access at /books
[INFO] The mapped volume for /books contains a Calibre database file 'metadata.db' which will be used
[INFO] The kindlegen directory exist already and will be used: /calibre-web/kindlegen
[INFO] Kindlegen application exists already in directory: /calibre-web/kindlegen
[INFO] kindlegen (Amazon Kindle Generator) will be linked into /calibre-web/app/vendor
> kindlegen link /calibre-web/app/vendor/kindlegen exists already and won't be recreated
[INFO] Launching Calibre-Web ...
[2023-02-04 17:31:40,307] INFO {cps.services.background_scheduler:32} APScheduler not found. Unable to schedule tasks.
Traceback (most recent call last):
File "/calibre-web/app/cps.py", line 31, in <module>
main()
File "/calibre-web/app/cps/main.py", line 26, in main
app = create_app()
File "/calibre-web/app/cps/__init__.py", line 175, in create_app
from .schedule import register_scheduled_tasks, register_startup_tasks
File "/calibre-web/app/cps/schedule.py", line 22, in <module>
from .services.background_scheduler import BackgroundScheduler, CronTrigger, use_APScheduler
ImportError: cannot import name 'CronTrigger' from 'cps.services.background_scheduler' (/calibre-web/app/cps/services/background_scheduler.py)

**Comment by rsulliv1** [comment]
I have the same problem on 6.9.2. 
must have started in the last month or so.
--
related: https://github.com/janeczku/calibre-web/issues/2673

**Comment by jack2002jack** [comment]
I have the same problem,too. 
When I try to pip install APScheduler,error occured " Could not build wheels for backports.zoneinfo, which is required to install pyproject.toml-based project".

**Comment by rsulliv1** [comment]
Haven't seen a solution yet. Alternate container images of calibre work. This repo's is currently doa for me.

⁣

**Comment by jack2002jack** [comment]
oops,recently i restarted my container,this isuse happened.I think this image pretty nice for it's additional function which make me can directly browsers digital books.wish it can be repaired.QWQ

**Comment by pranav-gilda** [comment]
> I have the same problem,too. When I try to pip install APScheduler,error occured " Could not build wheels for backports.zoneinfo, which is required to install pyproject.toml-based project".


I have the same problem as well, not with APScheduler but while trying to install dlib and face-recognition libraries for a project "Could not build wheels for backports.zoneinfo, which is required to install pyproject.toml-based project".
