### ISSUE TITLE
Can't start fresh container

### ISSUE THREAD

**Issue by Sparticuz** [Technosoft2000/docker-calibre-web#37]
Any ideas? All I've set is puid, pgid, and timezone's

````
        ,----,                                   ,
      ,/   .`|                                   ,
    ,`   .'  : .--.--.        ,----,        ,-.  ,
  ;    ;     //  /    '.    .'   .' \   ,--/ /|  ,
.'___,/    ,'|  :  /`. /  ,----,'    |,--. :/ |  ,
|    :     | ;  |  |--`   |    :  .  ;:  : ' /   ,
;    |.';  ; |  :  ;_     ;    |.'  / |  '  /    ,
`----'  |  |  \  \    `.  `----'/  ;  '  |  :    ,
    '   :  ;   `----.   \   /  ;  /   |  |   \   ,
    |   |  '   __ \  \  |  ;  /  /-,  '  : |. \  ,
    '   :  |  /  /`--'  / /  /  /.`|  |  | ' \ \ ,
    ;   |.'  '--'.     /./__;      :  '  : |--'  ,
    '---'      `--'---' |   :    .'   ;  |,'     ,
                        ;   | .'      '--'       ,
                        `---'                    ,
,
      PRESENTS ANOTHER AWESOME DOCKER IMAGE,
      ,
      ~~~~~         Calibre Web       ~~~~~,
                                           ,
[INFO] Docker image version: 1.2.3,
[INFO] Alpine Linux version: 3.8.0,
[WARNING] A group with id 1000 exists already [in use by calibre] and will be modified.,
[WARNING] The group calibre will be renamed to calibre,
[WARNING] A user with id 1000 exists already [in use by calibre].,
[WARNING] Create user calibre with temporary user id 999.,
adduser: user 'calibre' in use,
[WARNING] Assign non-unique user id 1000 to created user calibre,
usermod: no changes,
[INFO] Current active timezone is EDT,
ln: failed to create symbolic link '/etc/localtime': Resource busy,
[INFO] Container timezone is changed to: America/New_York,
[INFO] Change the ownership of /calibre-web (including subfolders) to calibre:calibre,
[INFO] Current git version is:,
git version 2.18.0,
[INFO] Checkout the latest Calibre-Web version ...,
[INFO] Autoupdate is active, try to pull the latest sources for Calibre-Web ...,
[INFO] ... current git status is,
On branch master,
Your branch is up to date with 'origin/master'.,
,
nothing to commit, working tree clean,
968cddf2b0c07ee39a62927c1a820c0f662c7ef8,
FO] ... pulling sources,
Already up to date.,
[INFO] ... git status after update is,
On branch master,
Your branch is up to date with 'origin/master'.,
,
nothing to commit, working tree clean,
968cddf2b0c07ee39a62927c1a820c0f662c7ef8,
[INFO] Config directory option is DEACTIVATED,
> due this the Calibre books directory /books will be used to store the configuration,
[INFO] Checking permissions of the config directory: /books,
> Output is: 775 calibre 1000 calibre 1000,
> Permissions: 775,
> Assigned group: calibre,
> Assigned group ID: 1000,
> Assigned owner: calibre,
> Assigned owner ID: 1000,
> Using permissions for checks: 0775,
> Check if the group calibre has write access at /books,
> The group calibre has write access at /books,
[INFO] 'app.db' and 'gdrive.db' will be linked into /books,
> 'app.db' link /calibre-web/app/app.db exists already and won't be recreated,
> create 'gdrive.db' link /calibre-web/app/gdrive.db assigned to source /books/gdrive.db,
ln: failed to create symbolic link '/calibre-web/app/gdrive.db': File exists,
> change the ownership of /calibre-web/app/gdrive.db to calibre:calibre,
[INFO] Checking permissions of the books directory: /books,
> Output is: 775 calibre 1000 calibre 1000,
> Permissions: 775,
> Assigned group: calibre,
> Assigned group ID: 1000,
> Assigned owner: calibre,
> Assigned owner ID: 1000,
> Using permissions for checks: 0775,
> Check if the group calibre has write access at /books,
> The group calibre has write access at /books,
[INFO] The mapped volume for /books contains a Calibre database file 'metadata.db' which will be used,
[INFO] The kindlegen directory exist already and will be used: /calibre-web/kindlegen,
[INFO] Kindlegen application exists already in directory: /calibre-web/kindlegen,
[INFO] kindlegen (Amazon Kindle Generator) will be linked into /calibre-web/app/vendor,
> kindlegen link /calibre-web/app/vendor/kindlegen exists already and won't be recreated,
[INFO] Launching Calibre-Web ...,
Traceback (most recent call last):,
  File "/calibre-web/app/cps.py", line 13, in <module>,
    from cps.server import Server,
  File "/calibre-web/app/cps/server.py", line 20, in <module>,
    import web,
  File "/calibre-web/app/cps/web.py", line 45, in <module>,
    import ub,
  File "/calibre-web/app/cps/ub.py", line 769, in <module>,
    Base.metadata.create_all(engine),
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 4005, in create_all,
    tables=tables),
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor,
    conn._run_visitor(visitorcallable, element, **kwargs),
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor,
    **kwargs).traverse_single(element),
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single,
    return meth(obj, **kw),
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata,
    _is_metadata_operation=True),
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single,
    return meth(obj, **kw),
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table,
    include_foreign_key_constraints=include_foreign_key_constraints,
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute,
    return meth(self, multiparams, params),
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection,
    return connection._execute_ddl(self, multiparams, params),
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1009, in _execute_ddl,
    compiled,
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context,
    context),
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception,
    exc_info,
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause,
    reraise(type(exception), exception, tb=exc_tb, cause=cause),
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context,
    context),
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute,
    cursor.execute(statement, parameters),
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'\nCREATE TABLE settings (\n\tid INTEGER NOT NULL, \n\tmail_server VARCHAR, \n\tmail_port INTEGER, \n\tmail_use_ssl SMALLINT, \n\tmail_login VARCHAR, \n\tmail_password VARCHAR, \n\tmail_from VARCHAR, \n\tconfig_calibre_dir VARCHAR, \n\tconfig_port INTEGER, \n\tconfig_certfile VARCHAR, \n\tconfig_keyfile VARCHAR, \n\tconfig_calibre_web_title VARCHAR, \n\tconfig_books_per_page INTEGER, \n\tconfig_random_books INTEGER, \n\tconfig_read_column INTEGER, \n\tconfig_title_regex VARCHAR, \n\tconfig_log_level SMALLINT, \n\tconfig_uploading SMALLINT, \n\tconfig_anonbrowse SMALLINT, \n\tconfig_public_reg SMALLINT, \n\tconfig_default_role SMALLINT, \n\tconfig_default_show SMALLINT, \n\tconfig_columns_to_ignore VARCHAR, \n\tconfig_use_google_drive BOOLEAN, \n\tconfig_google_drive_folder VARCHAR, \n\tconfig_google_drive_watch_changes_response VARCHAR, \n\tconfig_remote_login BOOLEAN, \n\tconfig_use_goodreads BOOLEAN, \n\tconfig_goodreads_api_key VARCHAR, \n\tconfig_goodreads_api_secret VARCHAR, \n\tconfig_mature_content_tags VARCHAR, \n\tconfig_logfile VARCHAR, \n\tconfig_ebookconverter INTEGER, \n\tconfig_converterpath VARCHAR, \n\tconfig_calibre VARCHAR, \n\tconfig_rarfile_location VARCHAR, \n\tPRIMARY KEY (id), \n\tCHECK (config_use_google_drive IN (0, 1)), \n\tCHECK (config_remote_login IN (0, 1)), \n\tCHECK (config_use_goodreads IN (0, 1))\n)\n\n'] (Background on this error at: http://sqlalche.me/e/e3q8),
````

**Comment by Sparticuz** [comment]
It looks like I had setup my bind's incorrectly. I redid them and it is working now.
