### ISSUE TITLE
Sometimes my ebook-converter hangs at 67% and no Cover

### ISSUE THREAD

**Issue by TheLux83** [Technosoft2000/docker-calibre-web#40]
Hey there,  
I was trying the new version of your calibre-web image and most of alle seems to work like a charm. But unfortunately, it seems, that the converter sometimes get stuck at 67%. At least in my container.  
I was trying to convert an EPUB File for sending to my kindle and it took 5 minutes where it shows 67% converted and after that, I've lost connection to my site and get an Internal Server Error.
The second try after restarting the container, it was again hanging at converting an EPUB File. Funny thing is, the first one that was okay, was and EPUB File, too.

My log says this: 
```
[2018-09-18 11:37:02,438] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/web.py", line 333, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 1254, in index
    entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
  File "/calibre-web/app/cps/web.py", line 524, in fill_indexpage
    .filter(db_filter).filter(common_filters()).all()))
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2836, in all
    return list(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2988, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3009, in _execute_and_instances
    close_with_result=True)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3018, in _get_bind_args
    **kw
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3000, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1035, in connection
    execution_options=execution_options)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1040, in _connection_for_bind
    engine, execution_options)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 388, in _connection_for_bind
    self._assert_active()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 264, in _assert_active
    "This session is in 'prepared' state; no further "
InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
::ffff:172.17.0.3 - - [2018-09-18 11:37:02] "GET / HTTP/1.1" 500 412 0.033701
[2018-09-18 11:37:04,381] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/web.py", line 333, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 1254, in index
    entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
  File "/calibre-web/app/cps/web.py", line 524, in fill_indexpage
    .filter(db_filter).filter(common_filters()).all()))
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2836, in all
    return list(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2988, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3009, in _execute_and_instances
    close_with_result=True)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3018, in _get_bind_args
    **kw
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3000, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1035, in connection
    execution_options=execution_options)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1040, in _connection_for_bind
    engine, execution_options)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 388, in _connection_for_bind
    self._assert_active()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 264, in _assert_active
    "This session is in 'prepared' state; no further "
InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
::ffff:172.17.0.3 - - [2018-09-18 11:37:04] "GET / HTTP/1.1" 500 412 0.005800
[2018-09-18 11:37:28,342] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/web.py", line 333, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 1254, in index
    entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
  File "/calibre-web/app/cps/web.py", line 524, in fill_indexpage
    .filter(db_filter).filter(common_filters()).all()))
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2836, in all
    return list(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2988, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3009, in _execute_and_instances
    close_with_result=True)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3018, in _get_bind_args
    **kw
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3000, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1035, in connection
    execution_options=execution_options)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1040, in _connection_for_bind
    engine, execution_options)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 388, in _connection_for_bind
    self._assert_active()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 264, in _assert_active
    "This session is in 'prepared' state; no further "
InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
::ffff:172.17.0.3 - - [2018-09-18 11:37:28] "GET / HTTP/1.1" 500 412 0.006676
[2018-09-18 11:38:10,473] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/web.py", line 333, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 1254, in index
    entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
  File "/calibre-web/app/cps/web.py", line 524, in fill_indexpage
    .filter(db_filter).filter(common_filters()).all()))
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2836, in all
    return list(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2988, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3009, in _execute_and_instances
    close_with_result=True)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3018, in _get_bind_args
    **kw
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3000, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1035, in connection
    execution_options=execution_options)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1040, in _connection_for_bind
    engine, execution_options)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 388, in _connection_for_bind
    self._assert_active()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 264, in _assert_active
    "This session is in 'prepared' state; no further "
InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
::ffff:172.17.0.3 - - [2018-09-18 11:38:10] "GET / HTTP/1.1" 500 412 0.012888
::ffff:192.168.200.3 - - [2018-09-18 11:38:18] "GET / HTTP/1.1" 302 621 0.009269
::ffff:192.168.200.3 - - [2018-09-18 11:38:18] "GET /login?next=%2F HTTP/1.1" 200 5040 0.010182
::ffff:192.168.200.3 - - [2018-09-18 11:38:18] "GET /static/js/libs/jquery.min.js?q=4a35612 HTTP/1.1" 200 84683 0.007039
::ffff:192.168.200.3 - - [2018-09-18 11:38:18] "GET /static/js/libs/bootstrap.min.js?q=5869c96 HTTP/1.1" 200 37348 0.011700
::ffff:192.168.200.3 - - [2018-09-18 11:38:18] "GET /static/css/style.css?q=dff85ef HTTP/1.1" 200 5670 0.005054
::ffff:192.168.200.3 - - [2018-09-18 11:38:18] "GET /static/js/libs/underscore-min.js?q=543feb1 HTTP/1.1" 200 16751 0.015152
::ffff:192.168.200.3 - - [2018-09-18 11:38:18] "GET /static/js/libs/intention.min.js?q=02ea871 HTTP/1.1" 200 6136 0.005134
::ffff:192.168.200.3 - - [2018-09-18 11:38:18] "GET /static/js/libs/jquery.form.js?q=08a2467 HTTP/1.1" 200 44195 0.017791
::ffff:192.168.200.3 - - [2018-09-18 11:38:18] "GET /static/js/libs/plugins.js?q=eda87d3 HTTP/1.1" 200 52256 0.006277
::ffff:192.168.200.3 - - [2018-09-18 11:38:18] "GET /static/js/libs/context.min.js?q=b9f1f37 HTTP/1.1" 200 1833 0.017722
::ffff:192.168.200.3 - - [2018-09-18 11:38:18] "GET /static/css/libs/bootstrap.min.css?q=ec3bb52 HTTP/1.1" 200 121505 0.123190
::ffff:192.168.200.3 - - [2018-09-18 11:38:18] "GET /static/js/main.js?q=b56303a HTTP/1.1" 200 6859 0.013354
::ffff:192.168.200.3 - - [2018-09-18 11:38:18] "GET /static/img/loader.gif?q=34015ca HTTP/1.1" 200 7108 0.014346
::ffff:192.168.200.3 - - [2018-09-18 11:38:18] "GET /static/css/fonts/GrandHotel-Regular.ttf HTTP/1.1" 200 44865 0.005207
::ffff:192.168.200.3 - - [2018-09-18 11:38:18] "GET /static/favicon.ico?q=14bd519 HTTP/1.1" 200 61966 0.004106
::ffff:172.17.0.3 - - [2018-09-18 11:38:35] "GET /login?next=%2F HTTP/1.1" 200 4903 0.016541
::ffff:172.17.0.3 - - [2018-09-18 11:38:35] "GET /static/css/libs/bootstrap.min.css?q=ec3bb52 HTTP/1.1" 200 121505 0.006313
::ffff:172.17.0.3 - - [2018-09-18 11:38:35] "GET /static/css/style.css?q=dff85ef HTTP/1.1" 200 5670 0.013071
::ffff:172.17.0.3 - - [2018-09-18 11:38:35] "GET /static/img/loader.gif?q=34015ca HTTP/1.1" 200 7108 0.006846
::ffff:172.17.0.3 - - [2018-09-18 11:38:35] "GET /static/js/libs/jquery.min.js?q=4a35612 HTTP/1.1" 200 84683 0.006325
::ffff:172.17.0.3 - - [2018-09-18 11:38:35] "GET /static/js/libs/bootstrap.min.js?q=5869c96 HTTP/1.1" 200 37348 0.015213
::ffff:172.17.0.3 - - [2018-09-18 11:38:35] "GET /static/js/libs/underscore-min.js?q=543feb1 HTTP/1.1" 200 16751 0.006500
::ffff:172.17.0.3 - - [2018-09-18 11:38:35] "GET /static/js/libs/intention.min.js?q=02ea871 HTTP/1.1" 200 6136 0.012062
::ffff:172.17.0.3 - - [2018-09-18 11:38:35] "GET /static/js/libs/context.min.js?q=b9f1f37 HTTP/1.1" 200 1833 0.005526
::ffff:172.17.0.3 - - [2018-09-18 11:38:35] "GET /static/js/libs/plugins.js?q=eda87d3 HTTP/1.1" 200 52256 0.017469
::ffff:172.17.0.3 - - [2018-09-18 11:38:35] "GET /static/js/libs/jquery.form.js?q=08a2467 HTTP/1.1" 200 44195 0.013917
::ffff:172.17.0.3 - - [2018-09-18 11:38:35] "GET /static/js/main.js?q=b56303a HTTP/1.1" 200 6859 0.015535
::ffff:172.17.0.3 - - [2018-09-18 11:38:35] "GET /static/css/fonts/GrandHotel-Regular.ttf HTTP/1.1" 200 44865 0.003755
::ffff:172.17.0.3 - - [2018-09-18 11:38:35] "GET /static/favicon.ico?q=14bd519 HTTP/1.1" 200 61966 0.004965
::ffff:172.17.0.3 - - [2018-09-18 11:38:36] "POST /login?next=%2F HTTP/1.1" 302 1009 0.095847
[2018-09-18 11:38:36,783] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/web.py", line 333, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 1254, in index
    entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
  File "/calibre-web/app/cps/web.py", line 524, in fill_indexpage
    .filter(db_filter).filter(common_filters()).all()))
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2836, in all
    return list(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2988, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3009, in _execute_and_instances
    close_with_result=True)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3018, in _get_bind_args
    **kw
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3000, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1035, in connection
    execution_options=execution_options)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1040, in _connection_for_bind
    engine, execution_options)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 388, in _connection_for_bind
    self._assert_active()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 264, in _assert_active
    "This session is in 'prepared' state; no further "
InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
::ffff:172.17.0.3 - - [2018-09-18 11:38:36] "GET / HTTP/1.1" 500 412 0.005987
::ffff:172.17.0.3 - - [2018-09-18 11:38:36] "GET /favicon.ico HTTP/1.1" 404 342 0.005119
::ffff:172.17.0.3 - - [2018-09-18 11:38:36] "GET /favicon.ico HTTP/1.1" 404 342 0.020954
::ffff:192.168.200.3 - - [2018-09-18 11:38:47] "GET / HTTP/1.1" 302 621 0.007672
::ffff:192.168.200.3 - - [2018-09-18 11:38:47] "GET /login?next=%2F HTTP/1.1" 200 5040 0.011651
::ffff:192.168.200.3 - - [2018-09-18 11:38:47] "GET /static/js/libs/bootstrap.min.js?q=5869c96 HTTP/1.1" 200 37348 0.005781
::ffff:192.168.200.3 - - [2018-09-18 11:38:47] "GET /static/js/libs/jquery.min.js?q=4a35612 HTTP/1.1" 200 84683 0.005607
::ffff:192.168.200.3 - - [2018-09-18 11:38:47] "GET /static/js/libs/intention.min.js?q=02ea871 HTTP/1.1" 200 6136 0.005023
::ffff:192.168.200.3 - - [2018-09-18 11:38:47] "GET /static/js/libs/underscore-min.js?q=543feb1 HTTP/1.1" 200 16751 0.013953
::ffff:192.168.200.3 - - [2018-09-18 11:38:48] "GET /static/css/fonts/GrandHotel-Regular.ttf HTTP/1.1" 200 44865 0.006537
::ffff:192.168.200.3 - - [2018-09-18 11:39:00] "POST /login?next=%2F HTTP/1.1" 302 998 0.171177
[2018-09-18 11:39:00,608] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/web.py", line 333, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 1254, in index
    entries, random, pagination = fill_indexpage(page, db.Books, True, [db.Books.timestamp.desc()])
  File "/calibre-web/app/cps/web.py", line 524, in fill_indexpage
    .filter(db_filter).filter(common_filters()).all()))
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2836, in all
    return list(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2988, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3009, in _execute_and_instances
    close_with_result=True)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3018, in _get_bind_args
    **kw
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3000, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1035, in connection
    execution_options=execution_options)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1040, in _connection_for_bind
    engine, execution_options)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 388, in _connection_for_bind
    self._assert_active()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 264, in _assert_active
    "This session is in 'prepared' state; no further "
InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
```
The first three conversions and sending worked without issues. But this was crashing my whole container.  
  
The second thing is, that 3 of 4 books that where sent, don't have the cover sent with them, only one book, which was an EPUB File, that was converted. I've tested an MOBI file and an PDF File which was converted. Both of them didn't send an cover with them.  
On my second try, I've send an MOBI file first. This came with an cover. But converting an EPUB file again crashed my container.  

I hope, I have posted everything you need to help me. I just wanted to send my books with an cover to my kindle ^^

**Comment by Technosoft2000** [comment]
Hi @TheLux83,

> I was trying to convert an EPUB File for sending to my kindle and it took 5 minutes where it shows 67% converted

Which converter do you use, which is configured and which version is shown at 'About':
 - kindlegen (Amazon)
 - ebook-convert (Calibre)

In such a case it would be also great if you can test if the conversion works successfully via the original **Calibre** application, because the container can use now this converter (ebook-convert) and if it doesn't work correct outside from the container it can't work correct inside the container too.

> I've lost connection to my site and get an Internal Server Error.

Okay so the application crashed completly - never had this situation yet, I'll try if I can reproduce such a similar situation. 

> The second thing is, that 3 of 4 books that where sent, don't have the cover sent with them, only one book, which was an EPUB File, that was converted.

Heard this issue mostly when **kindlegen** is used - btw. this issue has then something to-do with the converter (**kindlegen** or **ebook-convert**) and is not an issue of the container.
**ebook-convert** contains an argument `--cover` to pass a specific one to the resulting file, but this has to be handled then by Calibre-Web.

I can do a few tests and send the resulting file to my Kindle App on the tablet to see how it behaves (don't have a physical Amazon Kindle at the moment).

> On my second try, I've send an MOBI file first. This came with an cover. But converting an EPUB file again crashed my container.

Is it possible to provide the EPUB file which results in such a crash? Is the issue reproducable with the same EPUB file?


So I'll try different things to see what happens and let you know it if I've detected something :)

**Comment by TheLux83** [comment]
Hey @Technosoft2000,  
thanks for your reply. :)  
Oh man. Did I really wrote all this text without mentioning what converter I use? I'm really really sorry about it! :-D  
I'm using ths ebookconvert (Calibre) because of the possibility to send a cover with it.  
I've tested a few ebooks with calibre directly and it works without problems.  

The issue is reproducable with every other EPUB File. The converter doesn't convert PDF files, which is okay.  
Yesterday I've converted a bunch of EPUBs to MOBI directly in Calibre and sent them through calibre-web to my Kindle. This worked like a charm. Everything was there, inclusive the cover. Before that, I tried to convert the same ebooks via calibre-web and it was the same thing. 67% at converting and then crashing.

My about:
```
Sqlite - v3.24.0
Ixml - v4.2.4.0
Image Magick - ImageMagick 6.9.10-11 Q16 x86_64 2018-09-09 https://www.imagemagick.org
Flask - v1.0.2
Babel - v2.6.0
PyPdf - v1.26.0
Pysqlite - v2.6.0
Python - 2.7.15 (default, Aug 16 2018, 14:17:09)  [GCC 6.4.0]
Sqlalchemy - v1.2.11
Iso 639 - v0.4.5
Calibre converter - ebook-convert (calibre 3.31.0)
Requests - v2.19.1
Gevent - v1.3.6
Flask Login - v0.4.1
Flask Principal - v0.4.0
```
I hope this helps. If you need anything else, please let me know. Thanks again for your help! :-)

**Comment by Technosoft2000** [comment]
Hi @TheLux83 

today I've tested a lot of book conversion, from **EPUB -> MOBI** and **EPUB -> PDF** via the Edit Metadata page of each book and I had no issue at all with my Docker Container.

```
Program library - Installed Version
Sqlite -v3.24.0
lxml	- v4.2.4.0
Requests	- v2.19.1
Image Magick	- ImageMagick 6.9.10-11 Q16 x86_64 2018-09-09 https://www.imagemagick.org
Flask - v1.0.2
Babel -v2.6.0
pytz - v2018.5
PyPdf - v1.26.0
pySqlite - v2.6.0
Iso 639 - v0.4.5
Python - 2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]
Sqlalchemy - v1.2.11
Jinja2	v2.10
Wand Version - 0.4.4
Calibre converter - ebook-convert (calibre 3.31.0)
Werkzeug - v0.14.1
Gevent - v1.3.6
Flask Login - v0.4.1
Flask Principal - v0.4.0
```

Version	Details
11/25/18, 1:29 PM	Current version

Here a screenshot of my tasks - filenames have been made unrecognizable.
![calibre-web-tasks](https://user-images.githubusercontent.com/1690853/48984299-4088d680-f0fa-11e8-9273-56d092592b19.png)

The generated PDF and MOBI was then checked with the Calibre Viewer on my desktop machine and all files contains the cover.
