### ISSUE TITLE
Start-up: "AttributeError: 'NoneType' object has no attribute 'config_calibre_dir'"

### ISSUE THREAD

**Issue by BluebonnetSK** [Technosoft2000/docker-calibre-web#43]
After multiple re-installs and combing over my settings, I cannot figure out why my calibre-web docker will not start.  Note, I can successfully run the linuxserver/calibre-web docker, but I want to run this one for the ebook-converter feature. 

The docker never starts, it just keeps trying continually.  This section of log just repeats endlessly: 

```
        ,----,                                   ,
      ,/   .`|                                   ,
    ,`   .'  : .--.--.        ,----,        ,-.  ,
  ;    ;     //  /    '.    .'   .' \   ,--/ /|  ,
.'___,/    ,'|  :  /`. /  ,----,'    |,--. :/ |  ,
|    :     | ;  |  |--`   |    :  .  ;:  : ' /   ,
;    |.';  ; |  :  ;_     ;    |.'  / |  '  /    ,
`----'  |  |  \  \    `.  `----'/  ;  '  |  :    ,
    '   :  ;   `----.   \   /  ;  /   |  |   \   ,
    |   |  '   __ \  \  |  ;  /  /-,  '  : |. \  ,
    '   :  |  /  /`--'  / /  /  /.`|  |  | ' \ \ ,
    ;   |.'  '--'.     /./__;      :  '  : |--'  ,
    '---'      `--'---' |   :    .'   ;  |,'     ,
                        ;   | .'      '--'       ,
                        `---'                    ,
,
      PRESENTS ANOTHER AWESOME DOCKER IMAGE,
      ,
      ~~~~~         Calibre Web       ~~~~~,
                                           ,
[INFO] Docker image version: 1.2.3,
[INFO] Alpine Linux version: 3.8.0,
[WARNING] A group with id 1000 exists already [in use by calibre] and will be modified.,
[WARNING] The group calibre will be renamed to calibre,
[WARNING] A user with id 1000 exists already [in use by calibre].,
[WARNING] Create user calibre with temporary user id 999.,
[WARNING] Assign non-unique user id 1000 to created user calibre,
adduser: user 'calibre' in use,
usermod: no changes,
[INFO] Current active timezone is CET,
[INFO] Change the ownership of /calibre-web (including subfolders) to calibre:calibre,
[INFO] Current git version is:,
git version 2.18.0,
[INFO] Checkout the latest Calibre-Web version ...,
[INFO] Autoupdate is active, try to pull the latest sources for Calibre-Web ...,
[INFO] ... current git status is,
On branch master,
Your branch is up to date with 'origin/master'.,
,
nothing to commit, working tree clean,
dfa17956c908b814b035bf942494ba3450beeccf,
FO] ... pulling sources,
Already up to date.,
[INFO] ... git status after update is,
On branch master,
Your branch is up to date with 'origin/master'.,
,
nothing to commit, working tree clean,
dfa17956c908b814b035bf942494ba3450beeccf,
[INFO] Config directory option is DEACTIVATED,
> due this the Calibre books directory /books will be used to store the configuration,
[INFO] Checking permissions of the config directory: /books,
> Output is: 755 calibre 1000 calibre 1000,
> Permissions: 755,
> Assigned group: calibre,
> Assigned group ID: 1000,
> Assigned owner: calibre,
> Assigned owner ID: 1000,
> Using permissions for checks: 0755,
> The user calibre:1000 is the owner and has write access at /books,
[INFO] 'app.db' and 'gdrive.db' will be linked into /books,
> 'app.db' link /calibre-web/app/app.db exists already and won't be recreated,
> 'gdrive.db' link /calibre-web/app/gdrive.db exists already and won't be recreated,
[INFO] Checking permissions of the books directory: /books,
> Output is: 755 calibre 1000 calibre 1000,
> Permissions: 755,
> Assigned group: calibre,
> Assigned group ID: 1000,
> Assigned owner: calibre,
> Assigned owner ID: 1000,
> Using permissions for checks: 0755,
> The user calibre:1000 is the owner and has write access at /books,
[INFO] The mapped volume for /books contains a Calibre database file 'metadata.db' which will be used,
[INFO] The kindlegen directory exist already and will be used: /calibre-web/kindlegen,
[INFO] Kindlegen application exists already in directory: /calibre-web/kindlegen,
[INFO] kindlegen (Amazon Kindle Generator) will be linked into /calibre-web/app/vendor,
> kindlegen link /calibre-web/app/vendor/kindlegen exists already and won't be recreated,
[INFO] Launching Calibre-Web ...,
Traceback (most recent call last):,
  File "/calibre-web/app/cps.py", line 13, in <module>,
    from cps.server import Server,
  File "/calibre-web/app/cps/server.py", line 8, in <module>,
    import web,
  File "/calibre-web/app/cps/web.py", line 16, in <module>,
    import ub,
  File "/calibre-web/app/cps/ub.py", line 782, in <module>,
    config = Config(),
  File "/calibre-web/app/cps/ub.py", line 348, in __init__,
    self.loadSettings(),
  File "/calibre-web/app/cps/ub.py", line 353, in loadSettings,
    self.config_calibre_dir = data.config_calibre_dir,
AttributeError: 'NoneType' object has no attribute 'config_calibre_dir',
```
As a second issue, this line in the log concerns me: 
```[INFO] Config directory option is DEACTIVATED,```
because I have USE_CONFIG_DIR set to true, and have set the following volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/mnt/unionfs/Media/Books/Calibre_Library:/books"
      - "/mnt:/mnt"
      - "/opt/calibre-web/app:/calibre-web/app"
      - "/opt/calibre-web/config:/calibre-web/config"
      - "/opt/calibre-web/kindlegen:/calibre-web/kindlegen"
      - "/opt/calibre:/opt/calibre"

I running this on a headless Ubuntu 18.04.

_Originally posted by @BluebonnetSK in https://github.com/Technosoft2000/docker-calibre-web/issues/12#issuecomment-439788729_

**Comment by Technosoft2000** [comment]
Hi @BluebonnetSK,

I'll create a VM with Ubuntu 18.04 and test the behavior in the next days, I'll give you feedback as soon as possible.

**Comment by Technosoft2000** [comment]
Today I've done the tests on a Virtual Machine with the osboxes.org prepared Ubuntu 18.04.01 image.
I've used the following steps to create a similar container like you:

**1. check the UID & GID and create the application directories**
![01_create_directories](https://user-images.githubusercontent.com/1690853/48982476-6060d000-f0e3-11e8-9821-bade01486433.png)

**2. change the owner of the application directories (it works with root too)**
![02_chown](https://user-images.githubusercontent.com/1690853/48982475-6060d000-f0e3-11e8-94f1-1a5f946db3cb.png)

**3. pull the latest docker image**
![03_docker_pull](https://user-images.githubusercontent.com/1690853/48982474-6060d000-f0e3-11e8-95ea-16a1ea454058.png)

**4. check the directory layout again and the owner of it **
![04_check_dir_1](https://user-images.githubusercontent.com/1690853/48982473-6060d000-f0e3-11e8-8423-a42c8b8a044a.png)

![05_check_dir_2](https://user-images.githubusercontent.com/1690853/48982472-5fc83980-f0e3-11e8-9f3d-3a9f19cec5e7.png)

**5. create the container with the detected UID & GID and with the created application directories**
![06_create_container](https://user-images.githubusercontent.com/1690853/48982471-5fc83980-f0e3-11e8-89ba-dc25e3090d57.png)

**6. start the created container the first time**

I get the following log via `docker logs -f calibre-web`

```
root@osboxes:~# 
root@osboxes:~# docker start calibre-web
calibre-web
root@osboxes:~# docker logs -f calibre-web
        ,----,                                   
      ,/   .`|                                   
    ,`   .'  : .--.--.        ,----,        ,-.  
  ;    ;     //  /    '.    .'   .' \   ,--/ /|  
.'___,/    ,'|  :  /`. /  ,----,'    |,--. :/ |  
|    :     | ;  |  |--`   |    :  .  ;:  : ' /   
;    |.';  ; |  :  ;_     ;    |.'  / |  '  /    
`----'  |  |  \  \    `.  `----'/  ;  '  |  :    
    '   :  ;   `----.   \   /  ;  /   |  |   \   
    |   |  '   __ \  \  |  ;  /  /-,  '  : |. \  
    '   :  |  /  /`--'  / /  /  /.`|  |  | ' \ \ 
    ;   |.'  '--'.     /./__;      :  '  : |--'  
    '---'      `--'---' |   :    .'   ;  |,'     
                        ;   | .'      '--'       
                        `---'                    

      PRESENTS ANOTHER AWESOME DOCKER IMAGE
      
      ~~~~~         Calibre Web       ~~~~~
                                           
[INFO] Docker image version: 1.2.3
[INFO] Alpine Linux version: 3.8.0
[INFO] Create group calibre with id 1000
[INFO] Create user calibre with id 1000
[INFO] Current active timezone is EST
ln: failed to create symbolic link '/etc/localtime': Resource busy
[INFO] Container timezone is changed to: UTC
[INFO] Change the ownership of /calibre-web (including subfolders) to calibre:calibre
[INFO] Current git version is:
git version 2.18.0
[INFO] Checkout the latest Calibre-Web version ...
[INFO] ... git clone -b master --single-branch https://github.com/janeczku/calibre-web.git /calibre-web/app -v
Cloning into '/calibre-web/app'...
POST git-upload-pack (189 bytes)
[INFO] Autoupdate is active, try to pull the latest sources for Calibre-Web ...
[INFO] ... current git status is
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
64b1b830d60ee842ad1060fd113ed32abbf1dd19
[INFO] ... pulling sources
Already up to date.
[INFO] ... git status after update is
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
64b1b830d60ee842ad1060fd113ed32abbf1dd19
[INFO] Config directory option is ACTIVATED
> due this the directory /calibre-web/config will be used to store the configuration
[INFO] Change the ownership of /calibre-web/config (including subfolders) to calibre:calibre
[INFO] Checking permissions of the config directory: /calibre-web/config
> Output is: 755 calibre 1000 calibre 1000
> Permissions: 755
> Assigned group: calibre
> Assigned group ID: 1000
> Assigned owner: calibre
> Assigned owner ID: 1000
> Using permissions for checks: 0755
> The user calibre:1000 is the owner and has write access at /calibre-web/config
[INFO] 'app.db' and 'gdrive.db' will be linked into /calibre-web/config
> create 'app.db' link /calibre-web/app/app.db assigned to source /calibre-web/config/app.db
> change the ownership of /calibre-web/app/app.db to calibre:calibre
> create 'gdrive.db' link /calibre-web/app/gdrive.db assigned to source /calibre-web/config/gdrive.db
> change the ownership of /calibre-web/app/gdrive.db to calibre:calibre
[INFO] Checking permissions of the books directory: /books
> Output is: 755 calibre 1000 calibre 1000
> Permissions: 755
> Assigned group: calibre
> Assigned group ID: 1000
> Assigned owner: calibre
> Assigned owner ID: 1000
> Using permissions for checks: 0755
> The user calibre:1000 is the owner and has write access at /books
[WARNING] The mapped volume for /books doesn't contain a Calibre database file 'metadata.db'
> Due this an inital Calibre database file 'metadata.db' and 'metadata_db_prefs_backup.json' will be copied to /books
[INFO] The kindlegen directory exist already and will be used: /calibre-web/kindlegen
[INFO] Downloading kindlegen from http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz into directory: /calibre-web/kindlegen/kindlegen_linux_2.6_i386_v2_9.tar.gz
--2018-11-25 12:37:23--  http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz
Resolving kindlegen.s3.amazonaws.com... 52.216.108.51
Connecting to kindlegen.s3.amazonaws.com|52.216.108.51|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10813137 (10M) [application/x-gzip]
Saving to: '/calibre-web/kindlegen/kindlegen_linux_2.6_i386_v2_9.tar.gz'

     0K .......... .......... .......... .......... ..........  0%  159K 66s
    50K .......... .......... .......... .......... ..........  0%  227K 56s
   100K .......... .......... .......... .......... ..........  1%  358K 47s
   150K .......... .......... .......... .......... ..........  1%  276K 44s
   200K .......... .......... .......... .......... ..........  2%  433K 40s
   250K .......... .......... .......... .......... ..........  2%  242K 40s
   300K .......... .......... .......... .......... ..........  3%  455K 38s
   350K .......... .......... .......... .......... ..........  3%  121K 43s
   400K .......... .......... .......... .......... ..........  4%  340K 41s
   450K .......... .......... .......... .......... ..........  4%  153K 44s
   500K .......... .......... .......... .......... ..........  5%  117K 47s
   550K .......... .......... .......... .......... ..........  5%  186K 48s
   600K .......... .......... .......... .......... ..........  6%  116K 50s
   650K .......... .......... .......... .......... ..........  6% 86.1K 55s
   700K .......... .......... .......... .......... ..........  7% 76.0K 59s
   750K .......... .......... .......... .......... ..........  7% 74.2K 64s
   800K .......... .......... .......... .......... ..........  8% 81.7K 67s
   850K .......... .......... .......... .......... ..........  8% 84.3K 69s
   900K .......... .......... .......... .......... ..........  8% 60.8K 73s
   950K .......... .......... .......... .......... ..........  9% 37.6K 82s
  1000K .......... .......... .......... .......... ..........  9% 52.8K 86s
  1050K .......... .......... .......... .......... .......... 10% 56.3K 89s
  1100K .......... .......... .......... .......... .......... 10% 55.0K 93s
  1150K .......... .......... .......... .......... .......... 11% 72.4K 94s
  1200K .......... .......... .......... .......... .......... 11% 66.4K 95s
  1250K .......... .......... .......... .......... .......... 12% 58.9K 97s
  1300K .......... .......... .......... .......... .......... 12% 61.6K 98s
  1350K .......... .......... .......... .......... .......... 13% 65.0K 99s
  1400K .......... .......... .......... .......... .......... 13% 59.3K 1m41s
  1450K .......... .......... .......... .......... .......... 14% 61.5K 1m42s
  1500K .......... .......... .......... .......... .......... 14% 54.3K 1m43s
  1550K .......... .......... .......... .......... .......... 15% 39.5K 1m47s
  1600K .......... .......... .......... .......... .......... 15% 52.9K 1m48s
  1650K .......... .......... .......... .......... .......... 16% 63.4K 1m48s
  1700K .......... .......... .......... .......... .......... 16% 60.3K 1m49s
  1750K .......... .......... .......... .......... .......... 17% 75.3K 1m48s
  1800K .......... .......... .......... .......... .......... 17% 65.0K 1m48s
  1850K .......... .......... .......... .......... .......... 17% 79.3K 1m48s
  1900K .......... .......... .......... .......... .......... 18% 94.3K 1m47s
  1950K .......... .......... .......... .......... .......... 18% 88.4K 1m46s
  2000K .......... .......... .......... .......... .......... 19% 70.0K 1m46s
  2050K .......... .......... .......... .......... .......... 19%  106K 1m44s
  2100K .......... .......... .......... .......... .......... 20% 26.3K 1m49s
  2150K .......... .......... .......... .......... .......... 20% 42.8K 1m50s
  2200K .......... .......... .......... .......... .......... 21% 56.5K 1m50s
  2250K .......... .......... .......... .......... .......... 21% 61.2K 1m50s
  2300K .......... .......... .......... .......... .......... 22% 74.1K 1m50s
  2350K .......... .......... .......... .......... .......... 22% 74.6K 1m49s
  2400K .......... .......... .......... .......... .......... 23% 56.4K 1m49s
  2450K .......... .......... .......... .......... .......... 23% 87.2K 1m48s
  2500K .......... .......... .......... .......... .......... 24% 74.7K 1m47s
  2550K .......... .......... .......... .......... .......... 24%  101K 1m46s
  2600K .......... .......... .......... .......... .......... 25% 92.7K 1m45s
  2650K .......... .......... .......... .......... .......... 25% 74.8K 1m44s
  2700K .......... .......... .......... .......... .......... 26% 73.9K 1m44s
  2750K .......... .......... .......... .......... .......... 26% 79.3K 1m43s
  2800K .......... .......... .......... .......... .......... 26% 70.3K 1m43s
  2850K .......... .......... .......... .......... .......... 27% 63.8K 1m42s
  2900K .......... .......... .......... .......... .......... 27% 54.6K 1m42s
  2950K .......... .......... .......... .......... .......... 28% 65.3K 1m42s
  3000K .......... .......... .......... .......... .......... 28% 80.3K 1m41s
  3050K .......... .......... .......... .......... .......... 29% 86.4K 1m40s
  3100K .......... .......... .......... .......... .......... 29%  100K 99s
  3150K .......... .......... .......... .......... .......... 30%  118K 98s
  3200K .......... .......... .......... .......... .......... 30% 94.2K 97s
  3250K .......... .......... .......... .......... .......... 31%  136K 95s
  3300K .......... .......... .......... .......... .......... 31% 59.6K 95s
  3350K .......... .......... .......... .......... .......... 32% 64.1K 95s
  3400K .......... .......... .......... .......... .......... 32% 73.0K 94s
  3450K .......... .......... .......... .......... .......... 33% 83.8K 93s
  3500K .......... .......... .......... .......... .......... 33% 92.7K 92s
  3550K .......... .......... .......... .......... .......... 34%  130K 91s
  3600K .......... .......... .......... .......... .......... 34%  124K 90s
  3650K .......... .......... .......... .......... .......... 35%  101K 89s
  3700K .......... .......... .......... .......... .......... 35%  135K 88s
  3750K .......... .......... .......... .......... .......... 35%  130K 87s
  3800K .......... .......... .......... .......... .......... 36%  131K 86s
  3850K .......... .......... .......... .......... .......... 36%  139K 85s
  3900K .......... .......... .......... .......... .......... 37%  133K 84s
  3950K .......... .......... .......... .......... .......... 37%  125K 83s
  4000K .......... .......... .......... .......... .......... 38%  143K 82s
  4050K .......... .......... .......... .......... .......... 38%  107K 81s
  4100K .......... .......... .......... .......... .......... 39%  133K 80s
  4150K .......... .......... .......... .......... .......... 39% 98.4K 79s
  4200K .......... .......... .......... .......... .......... 40% 52.2K 79s
  4250K .......... .......... .......... .......... .......... 40% 74.5K 78s
  4300K .......... .......... .......... .......... .......... 41% 78.3K 78s
  4350K .......... .......... .......... .......... .......... 41% 93.2K 77s
  4400K .......... .......... .......... .......... .......... 42% 87.3K 76s
  4450K .......... .......... .......... .......... .......... 42% 78.1K 76s
  4500K .......... .......... .......... .......... .......... 43% 89.8K 75s
  4550K .......... .......... .......... .......... .......... 43% 48.2K 75s
  4600K .......... .......... .......... .......... .......... 44% 48.6K 75s
  4650K .......... .......... .......... .......... .......... 44% 42.9K 75s
  4700K .......... .......... .......... .......... .......... 44% 59.1K 74s
  4750K .......... .......... .......... .......... .......... 45% 73.8K 74s
  4800K .......... .......... .......... .......... .......... 45% 66.9K 73s
  4850K .......... .......... .......... .......... .......... 46% 52.1K 73s
  4900K .......... .......... .......... .......... .......... 46% 48.8K 73s
  4950K .......... .......... .......... .......... .......... 47% 58.3K 72s
  5000K .......... .......... .......... .......... .......... 47% 73.9K 72s
  5050K .......... .......... .......... .......... .......... 48% 61.6K 71s
  5100K .......... .......... .......... .......... .......... 48% 61.2K 71s
  5150K .......... .......... .......... .......... .......... 49% 85.8K 70s
  5200K .......... .......... .......... .......... .......... 49% 87.5K 69s
  5250K .......... .......... .......... .......... .......... 50% 77.6K 69s
  5300K .......... .......... .......... .......... .......... 50% 94.9K 68s
  5350K .......... .......... .......... .......... .......... 51%  101K 67s
  5400K .......... .......... .......... .......... .......... 51% 83.5K 66s
  5450K .......... .......... .......... .......... .......... 52% 88.3K 66s
  5500K .......... .......... .......... .......... .......... 52% 97.9K 65s
  5550K .......... .......... .......... .......... .......... 53%  110K 64s
  5600K .......... .......... .......... .......... .......... 53%  101K 63s
  5650K .......... .......... .......... .......... .......... 53% 89.3K 63s
  5700K .......... .......... .......... .......... .......... 54% 82.5K 62s
  5750K .......... .......... .......... .......... .......... 54% 71.1K 61s
  5800K .......... .......... .......... .......... .......... 55% 48.1K 61s
  5850K .......... .......... .......... .......... .......... 55% 50.4K 61s
  5900K .......... .......... .......... .......... .......... 56% 50.8K 60s
  5950K .......... .......... .......... .......... .......... 56% 64.0K 60s
  6000K .......... .......... .......... .......... .......... 57% 64.5K 59s
  6050K .......... .......... .......... .......... .......... 57% 79.1K 58s
  6100K .......... .......... .......... .......... .......... 58% 34.2K 58s
  6150K .......... .......... .......... .......... .......... 58% 48.5K 58s
  6200K .......... .......... .......... .......... .......... 59% 58.4K 57s
  6250K .......... .......... .......... .......... .......... 59% 79.5K 57s
  6300K .......... .......... .......... .......... .......... 60% 88.5K 56s
  6350K .......... .......... .......... .......... .......... 60% 99.9K 55s
  6400K .......... .......... .......... .......... .......... 61%  116K 54s
  6450K .......... .......... .......... .......... .......... 61%  142K 53s
  6500K .......... .......... .......... .......... .......... 62%  177K 53s
  6550K .......... .......... .......... .......... .......... 62%  199K 52s
  6600K .......... .......... .......... .......... .......... 62%  182K 51s
  6650K .......... .......... .......... .......... .......... 63%  313K 50s
  6700K .......... .......... .......... .......... .......... 63%  189K 49s
  6750K .......... .......... .......... .......... .......... 64%  228K 48s
  6800K .......... .......... .......... .......... .......... 64%  357K 47s
  6850K .......... .......... .......... .......... .......... 65%  229K 46s
  6900K .......... .......... .......... .......... .......... 65%  319K 46s
  6950K .......... .......... .......... .......... .......... 66%  339K 45s
  7000K .......... .......... .......... .......... .......... 66%  291K 44s
  7050K .......... .......... .......... .......... .......... 67%  350K 43s
  7100K .......... .......... .......... .......... .......... 67%  287K 42s
  7150K .......... .......... .......... .......... .......... 68%  175K 41s
  7200K .......... .......... .......... .......... .......... 68%  470K 40s
  7250K .......... .......... .......... .......... .......... 69%  197K 40s
  7300K .......... .......... .......... .......... .......... 69%  209K 39s
  7350K .......... .......... .......... .......... .......... 70%  193K 38s
  7400K .......... .......... .......... .......... .......... 70%  246K 37s
  7450K .......... .......... .......... .......... .......... 71%  159K 37s
  7500K .......... .......... .......... .......... .......... 71%  179K 36s
  7550K .......... .......... .......... .......... .......... 71%  174K 35s
  7600K .......... .......... .......... .......... .......... 72%  211K 35s
  7650K .......... .......... .......... .......... .......... 72%  237K 34s
  7700K .......... .......... .......... .......... .......... 73%  170K 33s
  7750K .......... .......... .......... .......... .......... 73%  213K 32s
  7800K .......... .......... .......... .......... .......... 74%  156K 32s
  7850K .......... .......... .......... .......... .......... 74%  257K 31s
  7900K .......... .......... .......... .......... .......... 75%  121K 30s
  7950K .......... .......... .......... .......... .......... 75%  206K 30s
  8000K .......... .......... .......... .......... .......... 76%  139K 29s
  8050K .......... .......... .......... .......... .......... 76%  102K 28s
  8100K .......... .......... .......... .......... .......... 77% 87.6K 28s
  8150K .......... .......... .......... .......... .......... 77% 86.7K 27s
  8200K .......... .......... .......... .......... .......... 78% 58.2K 27s
  8250K .......... .......... .......... .......... .......... 78% 67.0K 26s
  8300K .......... .......... .......... .......... .......... 79% 74.3K 26s
  8350K .......... .......... .......... .......... .......... 79% 85.1K 25s
  8400K .......... .......... .......... .......... .......... 80% 68.3K 25s
  8450K .......... .......... .......... .......... .......... 80% 82.9K 24s
  8500K .......... .......... .......... .......... .......... 80% 81.8K 23s
  8550K .......... .......... .......... .......... .......... 81% 70.3K 23s
  8600K .......... .......... .......... .......... .......... 81% 44.1K 22s
  8650K .......... .......... .......... .......... .......... 82% 61.2K 22s
  8700K .......... .......... .......... .......... .......... 82% 53.4K 21s
  8750K .......... .......... .......... .......... .......... 83% 78.7K 21s
  8800K .......... .......... .......... .......... .......... 83% 60.8K 20s
  8850K .......... .......... .......... .......... .......... 84% 55.6K 20s
  8900K .......... .......... .......... .......... .......... 84% 57.7K 19s
  8950K .......... .......... .......... .......... .......... 85% 80.4K 19s
  9000K .......... .......... .......... .......... .......... 85% 70.0K 18s
  9050K .......... .......... .......... .......... .......... 86% 42.3K 17s
  9100K .......... .......... .......... .......... .......... 86% 40.1K 17s
  9150K .......... .......... .......... .......... .......... 87% 30.4K 17s
  9200K .......... .......... .......... .......... .......... 87% 48.5K 16s
  9250K .......... .......... .......... .......... .......... 88% 41.9K 15s
  9300K .......... .......... .......... .......... .......... 88% 58.9K 15s
  9350K .......... .......... .......... .......... .......... 89% 68.8K 14s
  9400K .......... .......... .......... .......... .......... 89% 85.4K 14s
  9450K .......... .......... .......... .......... .......... 89% 79.7K 13s
  9500K .......... .......... .......... .......... .......... 90%  110K 12s
  9550K .......... .......... .......... .......... .......... 90% 94.9K 12s
  9600K .......... .......... .......... .......... .......... 91%  100K 11s
  9650K .......... .......... .......... .......... .......... 91%  102K 11s
  9700K .......... .......... .......... .......... .......... 92%  119K 10s
  9750K .......... .......... .......... .......... .......... 92%  155K 9s
  9800K .......... .......... .......... .......... .......... 93%  140K 9s
  9850K .......... .......... .......... .......... .......... 93% 74.3K 8s
  9900K .......... .......... .......... .......... .......... 94% 59.2K 7s
  9950K .......... .......... .......... .......... .......... 94% 48.6K 7s
 10000K .......... .......... .......... .......... .......... 95% 67.9K 6s
 10050K .......... .......... .......... .......... .......... 95% 56.3K 6s
 10100K .......... .......... .......... .......... .......... 96% 78.7K 5s
 10150K .......... .......... .......... .......... .......... 96% 67.0K 4s
 10200K .......... .......... .......... .......... .......... 97% 40.3K 4s
 10250K .......... .......... .......... .......... .......... 97% 43.6K 3s
 10300K .......... .......... .......... .......... .......... 98% 64.5K 3s
 10350K .......... .......... .......... .......... .......... 98% 69.6K 2s
 10400K .......... .......... .......... .......... .......... 98% 74.9K 1s
 10450K .......... .......... .......... .......... .......... 99% 59.1K 1s
 10500K .......... .......... .......... .......... .......... 99% 69.8K 0s
 10550K .........                                             100% 94.5K=2m12s

2018-11-25 12:39:34 (80.3 KB/s) - '/calibre-web/kindlegen/kindlegen_linux_2.6_i386_v2_9.tar.gz' saved [10813137/10813137]

[INFO] Extracting kindlegen_linux_2.6_i386_v2_9.tar.gz into directory: /calibre-web/kindlegen
[INFO] Change the ownership of /calibre-web/kindlegen (including subfolders) to calibre:calibre
[INFO] kindlegen (Amazon Kindle Generator) will be linked into /calibre-web/app/vendor
[INFO] Creating the vendor directory: /calibre-web/app/vendor
[INFO] Change the ownership of /calibre-web/app/vendor (including subfolders) to calibre:calibre
> create kindlegen link /calibre-web/app/vendor/kindlegen assigned to source /calibre-web/kindlegen/kindlegen
> change the ownership of /calibre-web/app/vendor/kindlegen to calibre:calibre
[INFO] Creating directory for temporary directories and files: /tmp
[INFO] Change the ownership of /tmp (including subfolders) to calibre:calibre
[INFO] Launching Calibre-Web ...
[2018-11-25 12:39:39,349] INFO in web: Starting Calibre Web...
[2018-11-25 12:39:40,596] INFO in server: Starting Gevent server

```
**7. check if Calibre-Web is available via the browser**
![07_run_container](https://user-images.githubusercontent.com/1690853/48982470-5fc83980-f0e3-11e8-8bbf-740142d9b85a.png)


I didn't mapped the following two parts into my container

- /opt/calibre:/opt/calibre  <- this isn't needed but it also works when I add this volume
- /mnt:/mnt

and I don't have this mount point

- /mnt/unionfs/Media/Books/Calibre_Library:/books

So the Docker Image itself has no issue.

Try to make a container in the same way as I've done with an empty books folder and look how it behaves on your machine, maybe it has something to do with your Calibre Library folder.
