### ISSUE TITLE
Yesterday start calibre-web with error

### ISSUE THREAD

**Issue by yche2990** [Technosoft2000/docker-calibre-web#63]
Before yesterday, everything works perfect on my synology docker. 

After I stopped and restarted the service, it seems that it automatically updates some parameters before launching. 

However, I am not sure whether it is due to an update.

When I now start the server, it shows an error: "No handlers could be found for logger "cps.services""

When I tried to access the book to read from browser, it shows:

Internal Server Error
Could not build url for endpoint 'bookmark' with values ['book_format', 'book_id']. Did you mean u'web.bookmark' instead?
File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app response = self.full_dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request rv = self.handle_user_exception(e)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request rv = self.dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args)
File "/calibre-web/app/cps/web.py", line 146, in decorated_view return login_required(func)(*args, **kwargs)
File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view return func(*args, **kwargs)
File "/calibre-web/app/cps/web.py", line 207, in inner return f(*args, **kwargs)
File "/calibre-web/app/cps/web.py", line 1309, in read_book return render_title_template('read.html', bookid=book_id, title=_(u"Read a Book"), bookmark=bookmark)
File "/calibre-web/app/cps/web.py", line 240, in render_title_template *args, **kwargs)
File "/usr/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template context, ctx.app)
File "/usr/lib/python2.7/site-packages/flask/templating.py", line 117, in _render rv = template.render(context)
File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render return self.environment.handle_exception(exc_info, True)
File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception reraise(exc_type, exc_value, tb)
File "/calibre-web/app/cps/templates/read.html", line 86, in top-level template code bookmarkUrl: "{{ url_for('bookmark', book_id=bookid, book_format='EPUB') }}",
File "/usr/lib/python2.7/site-packages/flask/helpers.py", line 356, in url_for return appctx.app.handle_url_build_error(error, endpoint, values)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 2061, in handle_url_build_error reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.7/site-packages/flask/helpers.py", line 345, in url_for force_external=external)
File "/usr/lib/python2.7/site-packages/werkzeug/routing.py", line 2181, in build raise BuildError(endpoint, values, method, self)

The log file shows:

[2019-07-22 20:14:49,448]  INFO {cps:89} Starting Calibre Web...
[2019-07-22 20:14:49,651]  INFO {cps.server:140} Starting Gevent server on [::]:port
[2019-07-22 20:23:15,181] ERROR {flask.app:1761} Exception on /read/4826/epub [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/web.py", line 146, in decorated_view
    return login_required(func)(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 207, in inner
    return f(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 1309, in read_book
    return render_title_template('read.html', bookid=book_id, title=_(u"Read a Book"), bookmark=bookmark)
  File "/calibre-web/app/cps/web.py", line 240, in render_title_template
    *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/calibre-web/app/cps/templates/read.html", line 86, in top-level template code
    bookmarkUrl: "{{ url_for('bookmark', book_id=bookid, book_format='EPUB') }}",
  File "/usr/lib/python2.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/usr/lib/python2.7/site-packages/werkzeug/routing.py", line 2181, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'bookmark' with values ['book_format', 'book_id']. Did you mean u'web.bookmark' instead?

Can you please advise?

**Comment by yunzhongci** [comment]
I also encountered the same problem

**Comment by Technosoft2000** [comment]
I've tried it now and I can't reproduce the issue here - I've done the following steps:

1. docker stop calibre-web
2. docker start calibre-web
3. docker logs -f calibre-web

and I got the following output:
```
        ,----,                                   
      ,/   .`|                                   
    ,`   .'  : .--.--.        ,----,        ,-.  
  ;    ;     //  /    '.    .'   .' \   ,--/ /|  
.'___,/    ,'|  :  /`. /  ,----,'    |,--. :/ |  
|    :     | ;  |  |--`   |    :  .  ;:  : ' /   
;    |.';  ; |  :  ;_     ;    |.'  / |  '  /    
`----'  |  |  \  \    `.  `----'/  ;  '  |  :    
    '   :  ;   `----.   \   /  ;  /   |  |   \   
    |   |  '   __ \  \  |  ;  /  /-,  '  : |. \  
    '   :  |  /  /`--'  / /  /  /.`|  |  | ' \ \ 
    ;   |.'  '--'.     /./__;      :  '  : |--'  
    '---'      `--'---' |   :    .'   ;  |,'     
                        ;   | .'      '--'       
                        `---'                    

      PRESENTS ANOTHER AWESOME DOCKER IMAGE
      
      ~~~~~         Calibre Web       ~~~~~
                                           
[INFO] Docker image version: 1.3.2
[INFO] Alpine Linux version: 3.9.0
[WARNING] A group with id 100 exists already [in use by calibre] and will be modified.
[WARNING] The group calibre will be renamed to calibre
[WARNING] A user with id 1029 exists already [in use by calibre].
[WARNING] Create user calibre with temporary user id 999.
adduser: user 'calibre' in use
[WARNING] Assign non-unique user id 1029 to created user calibre
usermod: no changes
[INFO] Current active timezone is CEST
Sun Aug  4 20:39:03 CEST 2019
[INFO] Container timezone is changed to: Europe/Vienna
[INFO] Change the ownership of /calibre-web (including subfolders) to calibre:calibre
[INFO] Current git version is:
git version 2.20.1
[INFO] Checkout the latest Calibre-Web version ...
[INFO] Autoupdate is active, try to pull the latest sources for Calibre-Web ...
[INFO] ... current git status is
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
aba88ae53a33c6b40b501e5bddf4ab1460b03cf4
[INFO] ... pulling sources
From https://github.com/janeczku/calibre-web
   aba88ae..3eae2e9  master     -> origin/master
 * [new tag]         0.6.4      -> 0.6.4
Updating aba88ae..3eae2e9
Fast-forward
 .gitattributes                                     |    2 +-
 .gitignore                                         |    3 +
 cps/gdrive.py                                      |  158 +
 cps/gdriveutils.py                                 |  107 +-
 cps/helper.py                                      |  409 +-
 cps/isoLanguages.py                                |   50 +-
 cps/jinjia.py                                      |  117 +
 cps/logger.py                                      |  168 +
 cps/oauth.py                                       |  157 +
 cps/oauth_bb.py                                    |  349 ++
 cps/opds.py                                        |  329 +
 cps/pagination.py                                  |   77 +
 cps/redirect.py                                    |    2 +
 cps/reverseproxy.py                                |    3 +
 cps/static/css/images/black-10.png                 |  Bin 0 -> 88 bytes
 cps/static/css/images/black-25.png                 |  Bin 0 -> 88 bytes
 cps/static/css/images/black-33.png                 |  Bin 0 -> 88 bytes
 cps/static/css/images/icomoon/credits.txt          |    6 +
 .../icomoon/entypo-25px-000000/PNG/arrow.png       |  Bin 0 -> 160 bytes
 .../images/icomoon/entypo-25px-000000/PNG/cart.png |  Bin 0 -> 230 bytes
 .../icomoon/entypo-25px-000000/PNG/first.png       |  Bin 0 -> 172 bytes
 .../images/icomoon/entypo-25px-000000/PNG/last.png |  Bin 0 -> 167 bytes
 .../images/icomoon/entypo-25px-000000/PNG/list.png |  Bin 0 -> 117 bytes
 .../icomoon/entypo-25px-000000/PNG/list2.png       |  Bin 0 -> 98 bytes
 .../images/icomoon/entypo-25px-000000/PNG/loop.png |  Bin 0 -> 190 bytes
 .../icomoon/entypo-25px-000000/PNG/music.png       |  Bin 0 -> 191 bytes
 .../icomoon/entypo-25px-000000/PNG/pause.png       |  Bin 0 -> 152 bytes
 .../images/icomoon/entypo-25px-000000/PNG/play.png |  Bin 0 -> 162 bytes
 .../icomoon/entypo-25px-000000/PNG/shuffle.png     |  Bin 0 -> 280 bytes
 .../icomoon/entypo-25px-000000/PNG/volume.png      |  Bin 0 -> 169 bytes
 .../icomoon/entypo-25px-000000/SVG/arrow.svg       |    8 +
 .../images/icomoon/entypo-25px-000000/SVG/cart.svg |    8 +
 .../icomoon/entypo-25px-000000/SVG/first.svg       |    8 +
 .../images/icomoon/entypo-25px-000000/SVG/last.svg |    8 +
 .../images/icomoon/entypo-25px-000000/SVG/list.svg |    8 +
 .../icomoon/entypo-25px-000000/SVG/list2.svg       |    8 +
 .../images/icomoon/entypo-25px-000000/SVG/loop.svg |    8 +
 .../icomoon/entypo-25px-000000/SVG/music.svg       |    8 +
 .../icomoon/entypo-25px-000000/SVG/pause.svg       |    8 +
 .../images/icomoon/entypo-25px-000000/SVG/play.svg |    8 +
 .../icomoon/entypo-25px-000000/SVG/shuffle.svg     |    8 +
 .../icomoon/entypo-25px-000000/SVG/volume.svg      |    8 +
 .../icomoon/entypo-25px-ffffff/PNG/arrow.png       |  Bin 0 -> 165 bytes
 .../images/icomoon/entypo-25px-ffffff/PNG/cart.png |  Bin 0 -> 236 bytes
 .../icomoon/entypo-25px-ffffff/PNG/first.png       |  Bin 0 -> 179 bytes
 .../images/icomoon/entypo-25px-ffffff/PNG/last.png |  Bin 0 -> 170 bytes
 .../images/icomoon/entypo-25px-ffffff/PNG/list.png |  Bin 0 -> 117 bytes
 .../icomoon/entypo-25px-ffffff/PNG/list2.png       |  Bin 0 -> 99 bytes
 .../images/icomoon/entypo-25px-ffffff/PNG/loop.png |  Bin 0 -> 201 bytes
 .../icomoon/entypo-25px-ffffff/PNG/music.png       |  Bin 0 -> 195 bytes
 .../icomoon/entypo-25px-ffffff/PNG/pause.png       |  Bin 0 -> 154 bytes
 .../images/icomoon/entypo-25px-ffffff/PNG/play.png |  Bin 0 -> 166 bytes
 .../icomoon/entypo-25px-ffffff/PNG/shuffle.png     |  Bin 0 -> 291 bytes
 .../icomoon/entypo-25px-ffffff/PNG/volume.png      |  Bin 0 -> 165 bytes
 .../icomoon/entypo-25px-ffffff/SVG/arrow.svg       |    8 +
 .../images/icomoon/entypo-25px-ffffff/SVG/cart.svg |    8 +
 .../icomoon/entypo-25px-ffffff/SVG/first.svg       |    8 +
 .../images/icomoon/entypo-25px-ffffff/SVG/last.svg |    8 +
 .../images/icomoon/entypo-25px-ffffff/SVG/list.svg |    8 +
 .../icomoon/entypo-25px-ffffff/SVG/list2.svg       |    8 +
 .../images/icomoon/entypo-25px-ffffff/SVG/loop.svg |    8 +
 .../icomoon/entypo-25px-ffffff/SVG/music.svg       |    8 +
 .../icomoon/entypo-25px-ffffff/SVG/pause.svg       |    8 +
 .../images/icomoon/entypo-25px-ffffff/SVG/play.svg |    8 +
 .../icomoon/entypo-25px-ffffff/SVG/shuffle.svg     |    8 +
 .../icomoon/entypo-25px-ffffff/SVG/volume.svg      |    8 +
 .../icomoon/free-25px-000000/PNG/spinner.png       |  Bin 0 -> 293 bytes
 .../icomoon/free-25px-000000/SVG/spinner.svg       |    8 +
 .../icomoon/free-25px-ffffff/PNG/spinner.png       |  Bin 0 -> 299 bytes
 .../icomoon/free-25px-ffffff/SVG/spinner.svg       |    8 +
 cps/static/css/images/patterns/rubber_grip.png     |  Bin 0 -> 123 bytes
 cps/static/css/images/patterns/tasky_pattern.png   |  Bin 0 -> 104 bytes
 cps/static/css/images/patterns/textured_paper.png  |  Bin 0 -> 130482 bytes
 cps/static/css/images/patterns/tweed.png           |  Bin 0 -> 21309 bytes
 cps/static/css/images/patterns/wood_pattern.png    |  Bin 0 -> 103832 bytes
 .../css/images/patterns/wood_pattern_dark.png      |  Bin 0 -> 33072 bytes
 cps/static/css/images/patterns/woven.png           |  Bin 0 -> 1165 bytes
 cps/static/css/libs/bar-ui.css                     | 1001 ++++
 cps/static/css/listen.css                          |  114 +
 cps/static/css/style.css                           |   17 +
 cps/static/js/archive/archive.js                   |   67 +-
 cps/templates/list.html                            |   49 +-
 cps/templates/listenmp3.html                       |  238 +
 cps/templates/login.html                           |   19 +-
 cps/templates/logviewer.html                       |   15 +
 cps/templates/osd.xml                              |    4 +-
 cps/templates/read.html                            |    8 +-
 cps/templates/readcbr.html                         |    4 +-
 cps/translations/sv/LC_MESSAGES/messages.mo        |  Bin 47724 -> 43750 bytes
 cps/translations/sv/LC_MESSAGES/messages.po        | 1893 +++---
 cps/translations/uk/LC_MESSAGES/messages.mo        |  Bin 56594 -> 41338 bytes
 cps/translations/uk/LC_MESSAGES/messages.po        | 1789 +++---
 .../zh_Hans_CN/LC_MESSAGES/messages.mo             |  Bin 46504 -> 41713 bytes
 .../zh_Hans_CN/LC_MESSAGES/messages.po             | 1893 +++---
 cps/ub.py                                          |  686 +--
 cps/updater.py                                     |  215 +-
 cps/uploader.py                                    |  219 +-
 cps/web.py                                         | 3843 ++----------
 cps/worker.py                                      |  296 +-
 messages.pot                                       | 1499 ++---
 optional-requirements.txt                          |   13 +-
 setup.cfg                                          |   24 +-
 setup.py                                           |   24 +-
 test/Calibre-Web TestSummary.html                  |  611 +-
 189 files changed, 32967 insertions(+), 18593 deletions(-)
 rename readme.md => README.md (97%)
 create mode 100644 cps/about.py
 create mode 100644 cps/admin.py
 delete mode 100644 cps/book_formats.py
 create mode 100644 cps/config_sql.py
 create mode 100644 cps/constants.py
 create mode 100644 cps/editbooks.py
 create mode 100644 cps/gdrive.py
 create mode 100644 cps/jinjia.py
 create mode 100644 cps/logger.py
 create mode 100644 cps/oauth.py
 create mode 100644 cps/oauth_bb.py
 create mode 100644 cps/opds.py
 create mode 100644 cps/pagination.py
 create mode 100644 cps/services/__init__.py
 create mode 100644 cps/services/goodreads.py
 create mode 100644 cps/services/simpleldap.py
 create mode 100644 cps/shelf.py
 create mode 100644 cps/static/css/images/black-10.png
 create mode 100644 cps/static/css/images/black-25.png
 create mode 100644 cps/static/css/images/black-33.png
 create mode 100644 cps/static/css/images/icomoon/credits.txt
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-000000/PNG/arrow.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-000000/PNG/cart.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-000000/PNG/first.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-000000/PNG/last.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-000000/PNG/list.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-000000/PNG/list2.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-000000/PNG/loop.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-000000/PNG/music.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-000000/PNG/pause.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-000000/SVG/first.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-000000/SVG/last.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-000000/SVG/list.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-000000/SVG/list2.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-000000/SVG/loop.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-000000/SVG/music.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-000000/SVG/pause.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-000000/SVG/play.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-000000/SVG/shuffle.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-000000/SVG/volume.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/PNG/arrow.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/PNG/cart.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/PNG/first.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/PNG/last.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/PNG/list.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/PNG/list2.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/PNG/loop.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/PNG/music.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/PNG/pause.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/PNG/play.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/PNG/shuffle.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/PNG/volume.png
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/SVG/arrow.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/SVG/cart.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/SVG/first.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/SVG/last.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/SVG/list.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/SVG/list2.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/SVG/loop.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/SVG/music.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/SVG/pause.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/SVG/play.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/SVG/shuffle.svg
 create mode 100644 cps/static/css/images/icomoon/entypo-25px-ffffff/SVG/volume.svg
 create mode 100644 cps/static/css/images/icomoon/free-25px-000000/PNG/spinner.png
 create mode 100644 cps/static/css/images/icomoon/free-25px-000000/SVG/spinner.svg
 create mode 100644 cps/static/css/images/icomoon/free-25px-ffffff/PNG/spinner.png
 create mode 100644 cps/static/css/images/icomoon/free-25px-ffffff/SVG/spinner.svg
 create mode 100644 cps/static/css/images/patterns/credits.txt
 create mode 100644 cps/static/css/images/patterns/pinstriped_suit_vertical.png
 create mode 100644 cps/static/css/images/patterns/pool_table.png
 create mode 100644 cps/static/css/images/patterns/rubber_grip.png
 create mode 100644 cps/static/css/images/patterns/tasky_pattern.png
 create mode 100644 cps/static/css/images/patterns/textured_paper.png
 create mode 100644 cps/static/css/images/patterns/tweed.png
 create mode 100644 cps/static/css/images/patterns/wood_pattern.png
 create mode 100644 cps/static/css/images/patterns/wood_pattern_dark.png
 create mode 100644 cps/static/css/images/patterns/woven.png
 create mode 100644 cps/static/css/libs/bar-ui.css
 create mode 100644 cps/static/css/listen.css
 create mode 100644 cps/static/js/filter_list.js
 mode change 100755 => 100644 cps/static/js/io/bitstream.js
 create mode 100644 cps/static/js/libs/bar-ui.js
 create mode 100644 cps/static/js/libs/soundmanager2.js
 create mode 100644 cps/static/js/logviewer.js
 create mode 100644 cps/subproc_wrapper.py
 create mode 100644 cps/templates/listenmp3.html
 create mode 100644 cps/templates/logviewer.html
 create mode 100644 cps/templates/shelfdown.html
[INFO] ... git status after update is
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
3eae2e9c2cab8089e2579139b998498d93e6207f
[INFO] Config directory option is ACTIVATED
> due this the directory /calibre-web/config will be used to store the configuration
[INFO] Checking permissions of the config directory: /calibre-web/config
> Output is: 755 calibre 100 calibre 1029
> Permissions: 755
> Assigned group: calibre
> Assigned group ID: 100
[INFO] 'app.db' and 'gdrive.db' will be linked into /calibre-web/config
> 'app.db' link /calibre-web/app/app.db exists already and won't be recreated
> 'gdrive.db' link /calibre-web/app/gdrive.db exists already and won't be recreated
[INFO] Checking permissions of the books directory: /books
> Output is: 772 calibre 100 UNKNOWN 1026
> Permissions: 772
> Assigned group: calibre
> Assigned group ID: 100
> Assigned owner: UNKNOWN
> Assigned owner ID: 1026
> Using permissions for checks: 0772
> Everyone has write access at /books
[INFO] The mapped volume for /books contains a Calibre database file 'metadata.db' which will be used
[INFO] The kindlegen directory exist already and will be used: /calibre-web/kindlegen
[INFO] Kindlegen application exists already in directory: /calibre-web/kindlegen
[INFO] kindlegen (Amazon Kindle Generator) will be linked into /calibre-web/app/vendor
> kindlegen link /calibre-web/app/vendor/kindlegen exists already and won't be recreated
[INFO] Launching Calibre-Web ...
```

So my Calibre Web container is up and running.
I've at the moment no idea what could be the reason that your container doesn't start correctly anymore. I think in such a case the best way to deal is to remove the old container and create a new one.
