### ISSUE TITLE
[Consult] Some problems encountered during use

### ISSUE THREAD

**Issue by nn200433** [Technosoft2000/docker-calibre-web#67]
When you edit the metadata, upload the book cover or automatically get the book cover. The image has been uploaded to the server, but the book cover is still wrong.

![image](https://user-images.githubusercontent.com/15652213/63516671-fcf3b980-c51f-11e9-9ddc-0fc3fad3be63.png)

----

Preview epub online, I don't know why it is always showing loading, no response
![image](https://user-images.githubusercontent.com/15652213/63516947-9a4eed80-c520-11e9-8778-b9d75a9d2e13.png)

----

File Directory:

![image](https://user-images.githubusercontent.com/15652213/63517203-1c3f1680-c521-11e9-97a6-3fc34eedfdfe.png)

log file:
```
[2019-08-22 11:21:39,310]  INFO {cps:89} Starting Calibre Web...
[2019-08-22 11:21:39,311]  WARN {cps.config_sql:259} invalidating configuration
[2019-08-22 11:21:39,418]  INFO {cps.server:140} Starting Gevent server on [::]:8083
[2019-08-22 11:22:07,692]  WARN {cps.config_sql:259} invalidating configuration
[2019-08-22 11:22:49,003]  WARN {cps.config_sql:259} invalidating configuration
[2019-08-22 11:23:59,981]  WARN {cps.config_sql:259} invalidating configuration
[2019-08-22 11:38:44,016]  WARN {cps.config_sql:259} invalidating configuration
[2019-08-22 11:41:32,562]  WARN {cps.config_sql:259} invalidating configuration
[2019-08-22 11:41:35,912]  WARN {cps.config_sql:259} invalidating configuration
[2019-08-22 11:41:57,694]  INFO {cps:89} Starting Calibre Web...
[2019-08-22 11:41:57,697]  WARN {cps.config_sql:259} invalidating configuration
[2019-08-22 11:41:57,887]  INFO {cps.server:140} Starting Gevent server on [::]:8083
[2019-08-22 11:42:49,982]  INFO {cps:89} Starting Calibre Web...
[2019-08-22 11:42:49,983]  WARN {cps.config_sql:259} invalidating configuration
[2019-08-22 11:42:50,087]  INFO {cps.server:140} Starting Gevent server on [::]:8083
[2019-08-22 11:43:36,612]  WARN {cps.config_sql:259} invalidating configuration
[2019-08-22 12:01:56,379]  WARN {cps.uploader:204} Cannot extract cover image, using default: 'module' object is not callable
[2019-08-22 12:07:47,652]  INFO {cps.web:998} Serving book: Yi Ben Xiao Xiao De MyBatisYuan Ma Fen Xi Shu - [_] Zhong Bo
[2019-08-22 12:09:37,857] ERROR {cps.helper:539} File not found: /books/calibre/John Schember/Quick Start Guide (1)/Quick Start Guide - John Schember.epub
[2019-08-22 12:10:09,035] ERROR {cps.helper:283} Deleting book 1 failed, book path not valid: John Schember/Quick Start Guide (1)
[2019-08-22 12:11:25,298]  WARN {cps.uploader:204} Cannot extract cover image, using default: 'module' object is not callable
[2019-08-22 12:16:50,471] ERROR {flask.app:1761} Exception on /series [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/web.py", line 145, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 695, in series_list
    title=_(u"Series list"), page="serieslist", data="series")
  File "/calibre-web/app/cps/web.py", line 240, in render_title_template
    *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/calibre-web/app/cps/templates/list.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/calibre-web/app/cps/templates/layout.html", line 151, in top-level template code
    {% block body %}{% endblock %}
  File "/calibre-web/app/cps/templates/list.html", line 7, in block "body"
    {% if entries[0][0].sort %}
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
UndefinedError: list object has no element 0
[2019-08-22 12:17:07,510] ERROR {flask.app:1761} Exception on /series [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/web.py", line 145, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 695, in series_list
    title=_(u"Series list"), page="serieslist", data="series")
  File "/calibre-web/app/cps/web.py", line 240, in render_title_template
    *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/calibre-web/app/cps/templates/list.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/calibre-web/app/cps/templates/layout.html", line 151, in top-level template code
    {% block body %}{% endblock %}
  File "/calibre-web/app/cps/templates/list.html", line 7, in block "body"
    {% if entries[0][0].sort %}
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
UndefinedError: list object has no element 0
[2019-08-22 12:17:12,988] ERROR {flask.app:1761} Exception on /publisher [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/web.py", line 145, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 679, in publisher_list
    title=_(u"Publisher list"), page="publisherlist", data="publisher")
  File "/calibre-web/app/cps/web.py", line 240, in render_title_template
    *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/calibre-web/app/cps/templates/list.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/calibre-web/app/cps/templates/layout.html", line 151, in top-level template code
    {% block body %}{% endblock %}
  File "/calibre-web/app/cps/templates/list.html", line 7, in block "body"
    {% if entries[0][0].sort %}
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
UndefinedError: list object has no element 0
[2019-08-22 12:17:16,534] ERROR {flask.app:1761} Exception on /ratings [GET]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/calibre-web/app/cps/web.py", line 145, in decorated_view
    return func(*args, **kwargs)
  File "/calibre-web/app/cps/web.py", line 709, in ratings_list
    title=_(u"Ratings list"), page="ratingslist", data="ratings")
  File "/calibre-web/app/cps/web.py", line 240, in render_title_template
    *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/usr/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/calibre-web/app/cps/templates/list.html", line 1, in top-level template code
    {% extends "layout.html" %}
  File "/calibre-web/app/cps/templates/layout.html", line 151, in top-level template code
    {% block body %}{% endblock %}
  File "/calibre-web/app/cps/templates/list.html", line 7, in block "body"
    {% if entries[0][0].sort %}
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 411, in getitem
    return obj[argument]
UndefinedError: list object has no element 0
[2019-08-22 12:18:21,248]  INFO {cps.web:998} Serving book: A Li Ba Ba JavaKai Fa Shou Ce (Hua Shan Ban ) - A Li Ba Ba Yu  Java She Qu Kai Fa Zhe
[2019-08-22 12:33:58,549]  WARN {cps.uploader:97} cannot parse metadata, using default: Comment must not contain '--' (double-hyphen), line 48, column 51 (line 48)
[2019-08-22 12:40:53,267]  INFO {cps.worker:284} Book id 4 - target format of .mobi does not exist. Moving forward with convert.
[2019-08-22 12:42:13,463]  INFO {cps.web:998} Serving book: A Li Ba Ba JavaKai Fa Shou Ce (Hua Shan Ban ) - A Li Ba Ba Yu  Java She Qu Kai Fa Zhe
[2019-08-22 12:54:06,592]  INFO {cps:89} Starting Calibre Web...
[2019-08-22 12:54:06,702]  INFO {cps.server:140} Starting Gevent server on [::]:8083
[2019-08-22 12:54:48,396]  INFO {cps.worker:277} Book id 4 already converted to .mobi
[2019-08-22 12:59:33,775]  WARN {cps.uploader:97} cannot parse metadata, using default: Comment must not contain '--' (double-hyphen), line 48, column 51 (line 48)
```

**Comment by Technosoft2000** [comment]
I've to check if this is an issue of the docker container, but it could be a problem of the calibre-web application itself - please look at https://github.com/janeczku/calibre-web/ for the application development too :)

**Comment by Technosoft2000** [comment]
Closed because it is not an issue of the docker container.
