### ISSUE TITLE
Unable to write to DB. 

### ISSUE THREAD

**Issue by tbirdv6** [Technosoft2000/docker-calibre-web#82]
I am running into an issue when trying to edit books through calibre web. I can view, read, edit, but can not save. 

Docker was created like this:
`docker create --name=calibreweb --restart=always \
-v /windowsshare:/windowsshare \
-p 8084:8083 \
technosoft2000/calibre-web:latest`

Here are the logs. 

[2020-06-24 08:24:47,948]  WARN {cps.config_sql:297} Log path None not valid, falling back to default
[2020-06-24 08:24:49,056]  INFO {cps:98} Starting Calibre Web...
[2020-06-24 08:24:49,073]  WARN {cps.config_sql:324} invalidating configuration
[2020-06-24 08:24:49,211]  INFO {cps.server:144} Starting Gevent server on [::]:8083
[2020-06-24 08:26:19,832] ERROR {cps.editbooks:663} (sqlite3.OperationalError) attempt to write a readonly database
[SQL: UPDATE books SET pubdate=?, series_index=?, last_modified=? WHERE books.id = ?]
[parameters: (datetime.datetime(2006, 6, 20, 0, 0), u'1.0', '2020-06-24 08:26:19.823997', 725)]
(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/calibre-web/app/cps/editbooks.py", line 650, in edit_book
    calibre_db.session.commit()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 995, in _emit_update_statements
    statement, multiparams
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: UPDATE books SET pubdate=?, series_index=?, last_modified=? WHERE books.id = ?]
[parameters: (datetime.datetime(2006, 6, 20, 0, 0), u'1.0', '2020-06-24 08:26:19.823997', 725)]
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by tbirdv6** [comment]
Feel free to close this one under user error, this was a CIFS share permissions issue.
